{{- if .Values.gatewayClass.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.controller.gatewayClassName }}
  labels:
    {{- include "cf-tunnel-gw-ctrl.labels" . | nindent 4 }}
spec:
  controllerName: {{ .Values.controller.controllerName }}
{{- end }}
