{{- if or .Values.cloudflare.apiToken (and .Values.manageCloudflared.enabled .Values.manageCloudflared.tunnelToken) }}
{{- if not .Values.cloudflare.apiTokenSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cf-tunnel-gw-ctrl.fullname" . }}
  labels:
    {{- include "cf-tunnel-gw-ctrl.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.cloudflare.apiToken }}
  api-token: {{ .Values.cloudflare.apiToken | b64enc | quote }}
  {{- end }}
  {{- if and .Values.manageCloudflared.enabled .Values.manageCloudflared.tunnelToken (not .Values.manageCloudflared.tunnelTokenSecretName) }}
  tunnel-token: {{ .Values.manageCloudflared.tunnelToken | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
