apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cf-tunnel-gw-ctrl.serviceAccountName" . }}
  labels:
    {{- include "cf-tunnel-gw-ctrl.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
